using System.Collections.Concurrent;
using System.Reflection;
using System.Xml;
using System.Xml.XPath;

namespace FastEndpoints.Swagger;

/// <summary>
/// helper for reading XML documentation comments from assemblies without Namotion.Reflection.
/// uses the standard XML documentation files generated by the compiler.
/// </summary>
static class XmlDocHelper
{
    static readonly ConcurrentDictionary<Assembly, XPathDocument?> _xmlDocCache = new();
    static readonly ConcurrentDictionary<string, string?> _memberDocCache = new();

    /// <summary>
    /// gets the XML documentation summary for a type.
    /// </summary>
    internal static string? GetXmlDocsSummary(this Type type)
        => GetMemberDoc(type.Assembly, GetMemberName(type), "summary");

    /// <summary>
    /// gets the XML documentation remarks for a type.
    /// </summary>
    internal static string? GetXmlDocsRemarks(this Type type)
        => GetMemberDoc(type.Assembly, GetMemberName(type), "remarks");

    /// <summary>
    /// gets the XML documentation summary for a property.
    /// </summary>
    internal static string? GetXmlDocsSummary(this PropertyInfo prop)
        => GetMemberDoc(prop.DeclaringType!.Assembly, GetMemberName(prop), "summary");

    /// <summary>
    /// gets a specific XML documentation tag for a property.
    /// </summary>
    internal static string? GetXmlDocsTag(this PropertyInfo prop, string tagName)
        => GetMemberDoc(prop.DeclaringType!.Assembly, GetMemberName(prop), tagName);

    static string? GetMemberDoc(Assembly assembly, string memberName, string tagName)
    {
        var cacheKey = $"{memberName}:{tagName}";

        return _memberDocCache.GetOrAdd(
            cacheKey,
            _ =>
            {
                var doc = GetXmlDoc(assembly);

                if (doc is null)
                    return null;

                var nav = doc.CreateNavigator();
                var node = nav.SelectSingleNode($"/doc/members/member[@name='{memberName}']/{tagName}");

                if (node is null)
                    return null;

                var value = node.InnerXml.Trim();

                return string.IsNullOrEmpty(value) ? null : value;
            });
    }

    static XPathDocument? GetXmlDoc(Assembly assembly)
    {
        return _xmlDocCache.GetOrAdd(
            assembly,
            asm =>
            {
                var xmlPath = Path.ChangeExtension(asm.Location, ".xml");

                if (!File.Exists(xmlPath))
                    return null;

                try
                {
                    return new XPathDocument(xmlPath);
                }
                catch
                {
                    return null;
                }
            });
    }

    static string GetMemberName(Type type)
        => $"T:{type.FullName ?? type.Name}";

    static string GetMemberName(PropertyInfo prop)
    {
        var declaringType = prop.DeclaringType;

        return declaringType is not null
                   ? $"P:{declaringType.FullName ?? declaringType.Name}.{prop.Name}"
                   : $"P:{prop.Name}";
    }
}
